package com.leikai.po;
// default package
// Generated Oct 19, 2013 5:02:47 PM by Hibernate Tools 3.4.0.CR1

/**
 * Producttype generated by hbm2java
 */
public class Producttype implements java.io.Serializable
{

  private Integer id;
  private String name;

  public Producttype()
  {
  }

  public Producttype(String name)
  {
    this.name = name;
  }

  public Integer getId()
  {
    return this.id;
  }

  public void setId(Integer id)
  {
    this.id = id;
  }

  public String getName()
  {
    return this.name;
  }

  public void setName(String name)
  {
    this.name = name;
  }

}
