package com.leikai.po;
// default package
// Generated Oct 19, 2013 5:02:47 PM by Hibernate Tools 3.4.0.CR1

/**
 * Ptcolor generated by hbm2java
 */
public class Ptcolor implements java.io.Serializable
{

  private Integer id;
  private String color;

  public Ptcolor()
  {
  }

  public Ptcolor(String color)
  {
    this.color = color;
  }

  public Integer getId()
  {
    return this.id;
  }

  public void setId(Integer id)
  {
    this.id = id;
  }

  public String getColor()
  {
    return this.color;
  }

  public void setColor(String color)
  {
    this.color = color;
  }

}
