package com.leikai.po;

// default package
// Generated Nov 7, 2013 6:36:31 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Ptcolor generated by hbm2java
 */
public class Ptcolor implements java.io.Serializable
{

  private Integer id;
  private String color;
  private Integer opUserId;
  private Date createTime;

  public Ptcolor()
  {
  }

  public Ptcolor(String color)
  {
    this.color = color;
  }

  public Ptcolor(String color, Integer opUserId, Date createTime)
  {
    this.color = color;
    this.opUserId = opUserId;
    this.createTime = createTime;
  }

  public Integer getId()
  {
    return this.id;
  }

  public void setId(Integer id)
  {
    this.id = id;
  }

  public String getColor()
  {
    return this.color;
  }

  public void setColor(String color)
  {
    this.color = color;
  }

  public Integer getOpUserId()
  {
    return this.opUserId;
  }

  public void setOpUserId(Integer opUserId)
  {
    this.opUserId = opUserId;
  }

  public Date getCreateTime()
  {
    return this.createTime;
  }

  public void setCreateTime(Date createTime)
  {
    this.createTime = createTime;
  }

}
