package com.leikai.po;
// default package
// Generated Oct 19, 2013 5:02:47 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Ptdetails generated by hbm2java
 */
public class Ptdetails implements java.io.Serializable
{

  private int id;
  private Integer productId;
  private Integer btId;
  private Date date;
  private String opUser;

  public Ptdetails()
  {
  }

  public Ptdetails(int id)
  {
    this.id = id;
  }

  public Ptdetails(int id, Integer productId, Integer btId, Date date, String opUser)
  {
    this.id = id;
    this.productId = productId;
    this.btId = btId;
    this.date = date;
    this.opUser = opUser;
  }

  public int getId()
  {
    return this.id;
  }

  public void setId(int id)
  {
    this.id = id;
  }

  public Integer getProductId()
  {
    return this.productId;
  }

  public void setProductId(Integer productId)
  {
    this.productId = productId;
  }

  public Integer getBtId()
  {
    return this.btId;
  }

  public void setBtId(Integer btId)
  {
    this.btId = btId;
  }

  public Date getDate()
  {
    return this.date;
  }

  public void setDate(Date date)
  {
    this.date = date;
  }

  public String getOpUser()
  {
    return this.opUser;
  }

  public void setOpUser(String opUser)
  {
    this.opUser = opUser;
  }

}
