package com.leikai.po;

// default package
// Generated Nov 7, 2013 6:36:31 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Ptdetails generated by hbm2java
 */
public class Ptdetails implements java.io.Serializable
{

  private int id;
  private int poId;
  private int btId;
  private Integer num;
  private Integer opUserId;
  private Date date;

  public Ptdetails()
  {
  }

  public Ptdetails(int id, int poId, int btId)
  {
    this.id = id;
    this.poId = poId;
    this.btId = btId;
  }

  public Ptdetails(int id, int poId, int btId, Integer num, Integer opUserId, Date date)
  {
    this.id = id;
    this.poId = poId;
    this.btId = btId;
    this.num = num;
    this.opUserId = opUserId;
    this.date = date;
  }

  public int getId()
  {
    return this.id;
  }

  public void setId(int id)
  {
    this.id = id;
  }

  public int getPoId()
  {
    return this.poId;
  }

  public void setPoId(int poId)
  {
    this.poId = poId;
  }

  public int getBtId()
  {
    return this.btId;
  }

  public void setBtId(int btId)
  {
    this.btId = btId;
  }

  public Integer getNum()
  {
    return this.num;
  }

  public void setNum(Integer num)
  {
    this.num = num;
  }

  public Integer getOpUserId()
  {
    return this.opUserId;
  }

  public void setOpUserId(Integer opUserId)
  {
    this.opUserId = opUserId;
  }

  public Date getDate()
  {
    return this.date;
  }

  public void setDate(Date date)
  {
    this.date = date;
  }

}
