package com.leikai.po;
// default package
// Generated Oct 19, 2013 5:02:47 PM by Hibernate Tools 3.4.0.CR1

/**
 * Ptsize generated by hbm2java
 */
public class Ptsize implements java.io.Serializable
{

  private Integer id;
  private String size;

  public Ptsize()
  {
  }

  public Ptsize(String size)
  {
    this.size = size;
  }

  public Integer getId()
  {
    return this.id;
  }

  public void setId(Integer id)
  {
    this.id = id;
  }

  public String getSize()
  {
    return this.size;
  }

  public void setSize(String size)
  {
    this.size = size;
  }

}
