package com.lebk.po;

// default package
// Generated Nov 7, 2013 6:36:31 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Pttype generated by hbm2java
 */
public class Pttype implements java.io.Serializable
{

  private Integer id;
  private String type;
  private Integer opUserId;
  private Date createTime;

  public Pttype()
  {
  }

  public Pttype(String type)
  {
    this.type = type;
  }

  public Pttype(String type, Integer opUserId, Date createTime)
  {
    this.type = type;
    this.opUserId = opUserId;
    this.createTime = createTime;
  }

  public Integer getId()
  {
    return this.id;
  }

  public void setId(Integer id)
  {
    this.id = id;
  }

  public String getType()
  {
    return this.type;
  }

  public void setType(String type)
  {
    this.type = type;
  }

  public Integer getOpUserId()
  {
    return this.opUserId;
  }

  public void setOpUserId(Integer opUserId)
  {
    this.opUserId = opUserId;
  }

  public Date getCreateTime()
  {
    return this.createTime;
  }

  public void setCreateTime(Date createTime)
  {
    this.createTime = createTime;
  }

  public String toString()
  {

    return this.id + ":" + this.getType() + ":" + this.getOpUserId() + ":" + this.getCreateTime();
  }

}
