package com.lebk.po;

// default package
// Generated Nov 7, 2013 6:36:31 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable
{

  private Integer id;
  private String name;
  private String password;
  private Date lastLoginTime;
  private Date createTime;
  private Integer type;
  private Boolean isValid;
  private String email;

  public User()
  {
  }

  public User(String name)
  {
    this.name = name;
  }

  public User(String name, String password, Date lastLoginTime, Date createTime, Integer type, Boolean isValid, String email)
  {
    this.name = name;
    this.password = password;
    this.lastLoginTime = lastLoginTime;
    this.createTime = createTime;
    this.type = type;
    this.isValid = isValid;
    this.email = email;
  }

  public Integer getId()
  {
    return this.id;
  }

  public void setId(Integer id)
  {
    this.id = id;
  }

  public String getName()
  {
    return this.name;
  }

  public void setName(String name)
  {
    this.name = name;
  }

  public String getPassword()
  {
    return this.password;
  }

  public void setPassword(String password)
  {
    this.password = password;
  }

  public Date getLastLoginTime()
  {
    return this.lastLoginTime;
  }

  public void setLastLoginTime(Date lastLoginTime)
  {
    this.lastLoginTime = lastLoginTime;
  }

  public Date getCreateTime()
  {
    return this.createTime;
  }

  public void setCreateTime(Date createTime)
  {
    this.createTime = createTime;
  }

  public Integer getType()
  {
    return this.type;
  }

  public void setType(Integer type)
  {
    this.type = type;
  }

  public Boolean getIsValid()
  {
    return this.isValid;
  }

  public void setIsValid(Boolean isValid)
  {
    this.isValid = isValid;
  }

  public String getEmail()
  {
    return this.email;
  }

  public void setEmail(String email)
  {
    this.email = email;
  }

}
